apiVersion: v1
kind: Service
metadata:
  name: memenow-resource-manager
  labels:
    app: memenow-resource-manager
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: memenow-resource-manager
